FROM ghcr.io/zerotraceio/rust-build:1.31 as builder
COPY .  /zerotrace/
WORKDIR /zerotrace/agent
ARG GITHUB_REF_NAME
RUN cp docker/rust-proxy-config /usr/local/cargo/config && \
    cargo build --release && \
    cargo build --release --bin zerotrace-agent-ctl && \
    ls -alh target/release
FROM scratch
COPY --from=builder /zerotrace/agent/ /
